formatter: "markdown" # this is required
version: ""
header-from: terraform/main.tf
footer-from: ""
recursive:
  enabled: false
sections:
  show:
    - providers
    - inputs
    - outputs
content: |-
  {{ .Header }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Requirements }}

  {{ .Footer }}
output:
  file: ""
  mode: replace
  template: "<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->    "
output-values:
  enabled: false
  from: ""
sort:
  enabled: true
  by: name
settings:
  anchor: true
  color: false
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
