apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: node-http
  namespace: kube-system
spec:
  repo: https://bjw-s-labs.github.io/helm-charts
  chart: app-template
  targetNamespace: default
  createNamespace: false
  version: 4.1.1
  valuesContent: |-
    controllers:
      node-http:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/jdavid77/node-http
              tag: "replace"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            resources:
              limits:
                memory: 100Mi
              requests:
                cpu: 50m
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
    service:
      main:
        controller: node-http
        type: LoadBalancer
        ports:
          http:
            port: 8080
            protocol: TCP