name: API
on:
  push:
    branches: [main]
    paths:
      - "api/**"
permissions:
  contents: write
  packages: write
jobs:
  scan:
    name: Trivy
    uses: ./.github/workflows/trivy.yml
  build-deploy:
    name: Build-Deploy
    needs: scan
    uses: ./.github/workflows/build-deploy.yml
    secrets: inherit
