name: Login
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  terraform:
    name: Login VM
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_DEPLOY_KEY }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GOOGLE_CREDENTIALS }}'
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
      - id: 'ssh'
        run: |-
          gcloud compute ssh k3s-vm --zone=europe-west1-b --tunnel-through-iap --command="sudo kubectl get nodes"
