name: Login
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  terraform:
    name: Login VM
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: api
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_DEPLOY_KEY }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GOOGLE_CREDENTIALS }}'
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
      # - name: Get Latest Tag
      #   id: tag
      #   run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Update Manifest
        run: |
          sed -i 's/tag: "replace"/tag: "latest"/' manifests/chart.yaml
      - name: Copy and apply manifest
        run: |-
          gcloud compute scp ./manifests/chart.yaml k3s-vm:~/chart.yaml \
            --zone=europe-west1-b \
            --tunnel-through-iap

          gcloud compute ssh k3s-vm \
            --zone=europe-west1-b \
            --tunnel-through-iap \
            --command="kubectl apply -f ~/chart.yaml"
